# Generated by Django 4.1.7 on 2023-03-14 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Critter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tool_size', models.IntegerField(null=True)),
                ('directions_link', models.TextField(null=True)),
                ('pattern_type', models.CharField(max_length=50)),
                ('critter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftyCrittersapi.critter')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='craftyCrittersapi.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YarnForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftyCrittersapi.project')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftyCrittersapi.yarn')),
            ],
        ),
        migrations.AddField(
            model_name='critter',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftyCrittersapi.photo'),
        ),
        migrations.AddField(
            model_name='critter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('critter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftyCrittersapi.critter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='craftyCrittersapi.project')),
            ],
        ),
    ]
